const jobs = [
    {
      title: 'Lead Software Developer',
      company: 'Amazon',
      rating: 4.4,
      reviews: 1500,
      experience: '10+ Yrs',
      salary: '₹40 LPA',
      location: 'Bangalore',
      qualification: '10+ years of experience in software engineering...',
      skills: ['React', 'Node.js', 'AWS', 'Microservices'],
      posted: '2 Days Ago',
    },
    {
      title: 'Data Scientist',
      company: 'Google',
      rating: 4.7,
      reviews: 500,
      experience: '5+ Yrs',
      salary: '₹35 LPA',
      location: 'Hyderabad',
      qualification: '5+ years of experience with machine learning...',
      skills: ['Python', 'TensorFlow', 'Data Analysis'],
      posted: '1 Day Ago',
    },
    {
      title: 'Frontend Developer',
      company: 'Facebook',
      rating: 4.6,
      reviews: 1000,
      experience: '3-5 Yrs',
      salary: '₹25 LPA',
      location: 'Mumbai',
      qualification: '3+ years of experience in frontend technologies...',
      skills: ['HTML', 'CSS', 'JavaScript', 'React'],
      posted: 'Few Hours Ago',
    },
    {
      title: 'Cloud Engineer',
      company: 'Microsoft',
      rating: 4.5,
      reviews: 800,
      experience: '7+ Yrs',
      salary: '₹30 LPA',
      location: 'Chennai',
      qualification: '7+ years in cloud infrastructure development...',
      skills: ['Azure', 'Kubernetes', 'Docker', 'CI/CD'],
      posted: '3 Days Ago',
    },
    {
      title: 'DevOps Engineer',
      company: 'Netflix',
      rating: 4.8,
      reviews: 400,
      experience: '5-7 Yrs',
      salary: '₹28 LPA',
      location: 'Bangalore',
      qualification: '5+ years of experience in DevOps practices...',
      skills: ['Jenkins', 'AWS', 'CI/CD', 'Terraform'],
      posted: '1 Week Ago',
    },
    {
      title: 'Backend Engineer',
      company: 'Uber',
      rating: 4.4,
      reviews: 900,
      experience: '6+ Yrs',
      salary: '₹32 LPA',
      location: 'Pune',
      qualification: '6+ years in backend development...',
      skills: ['Java', 'Spring Boot', 'Microservices', 'AWS'],
      posted: '4 Days Ago',
    },
    {
      title: 'Mobile App Developer',
      company: 'Spotify',
      rating: 4.6,
      reviews: 350,
      experience: '4-6 Yrs',
      salary: '₹26 LPA',
      location: 'Delhi',
      qualification: '4+ years of experience in mobile app development...',
      skills: ['Flutter', 'iOS', 'Android', 'Kotlin'],
      posted: '2 Weeks Ago',
    },
    {
      title: 'Full Stack Developer',
      company: 'Swiggy',
      rating: 4.3,
      reviews: 750,
      experience: '5+ Yrs',
      salary: '₹27 LPA',
      location: 'Gurgaon',
      qualification: '5+ years of experience in full stack development...',
      skills: ['JavaScript', 'React', 'Node.js', 'MongoDB'],
      posted: '5 Days Ago',
    },
    {
      title: 'Cybersecurity Analyst',
      company: 'Cisco',
      rating: 4.5,
      reviews: 600,
      experience: '4-7 Yrs',
      salary: '₹29 LPA',
      location: 'Noida',
      qualification: '4+ years of experience in cybersecurity...',
      skills: ['Network Security', 'Firewalls', 'Penetration Testing', 'SIEM'],
      posted: '1 Month Ago',
    },
  ];
  
  export default jobs;
  